### ISSUE TITLE
Problem running on Windows PC 

### ISSUE THREAD

**Issue by Alex1996-alt** [StephanAkkerman/Crypto_Forecasting#53] opened 2024-08-17 21:16 UTC
Problems with running code on windows. Getting the following error see screenshot. Path issues model_output files (log_return works) but no files are generated for raw, scaled ... Conversely, the calculations for RMSE do not work either. Thanks for the help in advance
![Screenshot Python Code ](https://github.com/user-attachments/assets/e049f4ef-ae24-45cb-8ce6-dc1a7f8c8e66)

**Comment by Alex1996-alt** [comment] 2024-08-19 10:00
I managed to get the file creation working for the model_output. Unfortunately, the rmse files are now not being created properly. Getting the following error (see screenshot) 
![Screenshot 2024-08-19 120035](https://github.com/user-attachments/assets/9a1db5b5-3a96-42a2-a7ef-df75200a137f)

**Comment by StephanAkkerman** [comment] 2024-08-25 11:31
@Alex1996-alt It seems that the column 'close' is missing in your prediction data. Can you show me what is in your /pred_{period}.csv?

**Comment by Alex1996-alt** [comment] 2024-08-25 14:39
Hey thanks for your help. I will upload my output files maybe that is more helpfull to solve it:) 
[output.zip](https://github.com/user-attachments/files/16740681/output.zip)
[src.zip](https://github.com/user-attachments/files/16740682/src.zip)

**Comment by StephanAkkerman** [comment] 2024-08-25 15:54
I accidentally put the raw-to-log model in experiment/utils.py in line 82, you can delete this line and it should work then.

**Comment by Alex1996-alt** [comment] 2024-08-25 16:26
Hi you mean log_to_raw in line 82? I dont have raw_to_log  here (see screenshot) Thanks for your time :)
![image](https://github.com/user-attachments/assets/1c1959af-9ad2-4888-8294-b817515faf54)

**Comment by StephanAkkerman** [comment] 2024-08-25 16:47
@Alex1996-alt Yeah my bad I meant that one, it's deleted with the latest commit: https://github.com/StephanAkkerman/crypto-forecasting-benchmark/commit/ffe49db486560b176ccb50f9d012cd2f75a1eb2c

**Comment by Alex1996-alt** [comment] 2024-08-25 20:17
Hi thanks in advance for the help that is really very nice of you. I have at least made some progress and now I get the following error message. See screenshot. All rmse files could be generated except for scaled_to_raw. Thank you again hopefully you can help me with the next point :)
![image](https://github.com/user-attachments/assets/db44dfee-5f89-463d-a825-4c9b80769a08)
[src.zip](https://github.com/user-attachments/files/16741812/src.zip)

**Comment by StephanAkkerman** [comment] 2024-08-26 06:54
For this you can remove the scaled_to_raw in the list too, that should fix it. So the line 83 in this screenshot: https://github.com/StephanAkkerman/crypto-forecasting-benchmark/issues/53#issuecomment-2308914641

**Comment by Alex1996-alt** [comment] 2024-08-26 09:38
Hi, everything seems to be working fine for now thank you very much. A general question of understanding. What exactly are the output files such as log_to_raw, raw_to_log etc. relevant for and what exactly are we training the models for? As I understand it, only the raw, scaled and log returns are of interest to us, aren't they?

**Comment by StephanAkkerman** [comment] 2024-08-26 12:09
> What exactly are the output files such as log_to_raw, raw_to_log etc. relevant for

This is to see if the transformation of the data had any impact on the performance, for instance log_to_raw uses the model's forecast that was trained with logistic regression data and then the output is converted back into raw (close price). I did this to see if there would be big differences in transforming the output in comparison to transforming the input data.

> What exactly are we training the models for?

To predict one step ahead, for instance what the price of Bitcoin will be tomorrow given the last x days of data.

> only the raw, scaled and log returns are of interest to us, aren't they?

Yes, this is what we need as output and then all the other formats can be converted afterwards. If you are purely interested in getting the best performance you could drop the raw and maybe even the scaled (depending on the models you want to use).

**Comment by StephanAkkerman** [comment] 2024-08-26 12:10
Unfortunately, the website of the university is having difficulties right now it seems. I think if you're purely interested in finding out the best model, then reading through the paper would be the easiest. 

Would you mind sharing what your goal is?

**Comment by Alex1996-alt** [comment] 2024-08-26 12:50
Hey yes, among other things I want to see how the models perform and what relevance data properties have. I might look at a few other time frames and a few less models and cryptocurrencies. I also wanted to implement the Holt Winters model and see how much worse or maybe half as good the model performs. I'm currently writing my master's thesis and I'm trying to see if the somewhat simpler models like ARIMA and Holt Winters still perform well by implementing Holt Winters.

**Comment by StephanAkkerman** [comment] 2024-08-26 13:41
I've added the PDF since the website that's hosting my paper is currently down. Hopefully that helps you with a bit of the data properties. If you are looking for performance, then I would suggest looking into models that are built for cryptocurrency / stocks forecasting.

**Comment by Alex1996-alt** [comment] 2024-08-26 17:48
Thank you very much since I am an economist and not the best at programming your code and work is helping me really a lot :)

**Comment by StephanAkkerman** [comment] 2024-08-26 19:29
Glad to hear, let me know if you need any help!

**Comment by Alex1996-alt** [comment] 2024-09-01 21:07
Hi, I've run into another error (see the screenshot). It’s trying to access the file "Ljung-Box_log_return" in the Statistics folder, but unfortunately, that file doesn’t exist on my end. Could you please take a look at this or let me know in which script and function the file is generated? The screenshot also shows my Statistics folder with all the files created by the analysis.data_analysis_tests() function. If you need my current code for this, just let me know. Thanks a lot for your time!
![image](https://github.com/user-attachments/assets/7878b105-ce7b-4524-bd45-dc9126592596)

**Comment by StephanAkkerman** [comment] 2024-09-02 07:40
Good find, I improved that function but apparently there is still some old code left. I will try to fix it today. The data can now be found in `auto_correlation_results_log_returns` excel file. So the column for the Ljung-Box is located in there, instead of a separate file for this data.

**Comment by Alex1996-alt** [comment] 2024-09-02 08:11
All right, thanks. Please let me know when the error has been fixed. And thanks again for your time

**Comment by Alex1996-alt** [comment] 2024-09-02 08:55
Think I am missing a lot more files here 
![image](https://github.com/user-attachments/assets/082a4dd0-0cbf-4142-b35f-ada0b13d9da0)

**Comment by StephanAkkerman** [comment] 2024-09-02 15:26
@Alex1996-alt it should be fixed now, you can use the new data_properties.py file

**Comment by Alex1996-alt** [comment] 2024-09-02 16:41
Hi, first of all, thank you for taking the time here - I don't take that for granted. I am getting now a new error could you take a look? 
![image](https://github.com/user-attachments/assets/131c94b8-4f74-41e1-807d-b1c5363a5bbf)

**Comment by StephanAkkerman** [comment] 2024-09-02 17:39
@Alex1996-alt Thanks for reporting it once again, I updated volatility to automatically create the files if they do not exist

**Comment by Alex1996-alt** [comment] 2024-09-02 17:48
Hi I think we are getting close :) That is the next missing file and error 
![image](https://github.com/user-attachments/assets/bfcabbfc-0518-478a-a569-341185545500)

**Comment by StephanAkkerman** [comment] 2024-09-02 19:46
@Alex1996-alt I once did a large overhaul near the end of the thesis, which is why the code that is part of the beginning has some errors. Any missing file errors in data_properties should be fixed now.

**Comment by Alex1996-alt** [comment] 2024-09-02 20:19
Yeah no worries. I still thank you for helping me so much to get everything running. Unfortunately, I'm getting the following error now, any ideas? 
![image](https://github.com/user-attachments/assets/c2274a45-1eb8-4bbc-81b8-cd4f59a834de)

**Comment by StephanAkkerman** [comment] 2024-09-03 05:37
Should be fixed now!

**Comment by Alex1996-alt** [comment] 2024-09-03 08:36
Hey thanks. I am getting the next error :D Thank you so much for your time 
![image](https://github.com/user-attachments/assets/883a31d2-a667-4ddf-a704-967ff2039604)

**Comment by StephanAkkerman** [comment] 2024-09-03 15:26
I'll look into it in a bit and will do a full run locally to (hopefully) prevent future bugs

**Comment by Alex1996-alt** [comment] 2024-09-03 15:29
Thank you very much, please let me know as soon as everything is up and running. :)

**Comment by StephanAkkerman** [comment] 2024-09-03 18:49
@Alex1996-alt I improved both `analysis.data_analysis_tests()` and `analysis.forecast_statistical_tests()` and should work now without any issues. Let me know if there's anything else you find.

**Closed as completed** 2024-09-03 18:48 UTC

**Comment by Alex1996-alt** [comment] 2024-09-04 09:48
Hi yes everything is working well so far, thank you very much for your help. The only thing that is not yet saved are the comparison files in the output folder. Any idea what I can do best there?

**Comment by StephanAkkerman** [comment] 2024-09-04 13:57
@Alex1996-alt I have added the call to that function to main, so if your config is set up correctly it should run and create all comparisons

**Comment by Alex1996-alt** [comment] 2024-09-04 14:06
Nice thank you very much comparison files creation is working :) Getting one last error  for the analysis.market_factors_impact() function. Thanks for your time
![image](https://github.com/user-attachments/assets/694da73b-ee42-4995-b99e-c1ac6b2876af)

**Comment by StephanAkkerman** [comment] 2024-09-04 14:56
It has been fixed and will now output both test results, I set group_tf to False but you can also set it to True to see both results

**Comment by Alex1996-alt** [comment] 2024-09-06 10:39
hey thank you so much for your time everything is working fine so far :)

**Comment by meUsmanAshraf** [comment] 2024-09-09 11:47
hey how are you
